"""添加用户认证字段

Revision ID: 20260602_add_user_auth_fields
Revises: 
Create Date: 2026-06-02 15:18:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = '20260602_add_user_auth_fields'
down_revision = '577ac6ff6887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 添加新字段到用户表
    op.add_column('users', sa.Column('username', sa.String(32), nullable=True, comment='用户名'))
    op.add_column('users', sa.Column('hashed_password', sa.String(128), nullable=True, comment='密码哈希'))
    op.add_column('users', sa.Column('email', sa.String(128), nullable=True, comment='邮箱'))
    op.add_column('users', sa.Column('qq_openid', sa.String(64), nullable=True, comment='QQ openid'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, comment='账户是否激活'))
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True, comment='登录失败尝试次数'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True, comment='账户锁定截止时间'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'))
    
    # 创建索引
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_qq_openid', 'users', ['qq_openid'], unique=True)
    
    # 修改现有字段
    op.alter_column('users', 'openid',
                    existing_type=mysql.VARCHAR(length=64),
                    nullable=True,
                    comment='微信openid')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除索引
    op.drop_index('ix_users_qq_openid', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    
    # 删除字段
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'qq_openid')
    op.drop_column('users', 'email')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    
    # 恢复openid字段
    op.alter_column('users', 'openid',
                    existing_type=mysql.VARCHAR(length=64),
                    nullable=False,
                    comment='微信openid')
    
    # ### end Alembic commands ###
