"""initial

Revision ID: 577ac6ff6887
Revises: 
Create Date: 2026-06-02 14:34:16.469710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577ac6ff6887'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='景点名称'),
    sa.Column('address', sa.String(length=256), nullable=False, comment='详细地址'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='经度'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='城市'),
    sa.Column('district', sa.String(length=64), nullable=True, comment='区县'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='景点类别（公园、博物馆、商场等）'),
    sa.Column('subcategory', sa.String(length=64), nullable=True, comment='子类别'),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='评分（0-5）'),
    sa.Column('rating_count', sa.Integer(), nullable=True, comment='评分人数'),
    sa.Column('ticket_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='门票价格（0表示免费）'),
    sa.Column('opening_hours', sa.String(length=128), nullable=True, comment='开放时间'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签（如免费景点、亲子友好）'),
    sa.Column('highlights', sa.JSON(), nullable=True, comment='亮点介绍'),
    sa.Column('images', sa.JSON(), nullable=True, comment='景点图片'),
    sa.Column('description', sa.Text(), nullable=True, comment='景点描述'),
    sa.Column('source', sa.String(length=32), nullable=True, comment='数据来源'),
    sa.Column('source_id', sa.String(length=64), nullable=True, comment='来源ID'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态（0禁用 1正常）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='商家名称'),
    sa.Column('address', sa.String(length=256), nullable=False, comment='详细地址'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='经度'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='城市'),
    sa.Column('district', sa.String(length=64), nullable=True, comment='区县'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='商家类别（火锅、烧烤、日料等）'),
    sa.Column('subcategory', sa.String(length=64), nullable=True, comment='子类别'),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='评分（0-5）'),
    sa.Column('rating_count', sa.Integer(), nullable=True, comment='评分人数'),
    sa.Column('avg_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='人均消费（元）'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('business_hours', sa.String(length=128), nullable=True, comment='营业时间'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签（如人气最高、新开店铺）'),
    sa.Column('recommended_dishes', sa.JSON(), nullable=True, comment='推荐菜品'),
    sa.Column('images', sa.JSON(), nullable=True, comment='商家图片'),
    sa.Column('description', sa.Text(), nullable=True, comment='商家描述'),
    sa.Column('source', sa.String(length=32), nullable=True, comment='数据来源'),
    sa.Column('source_id', sa.String(length=64), nullable=True, comment='来源ID'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态（0禁用 1正常）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=256), nullable=False, comment='缓存键'),
    sa.Column('cache_value', sa.Text(), nullable=False, comment='缓存值'),
    sa.Column('expire_time', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=True, comment='微信openid'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='用户昵称'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='头像URL'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('attraction_ratings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attraction_id', sa.BigInteger(), nullable=False, comment='景点ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=1), nullable=False, comment='评分（0-5）'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评价内容'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_context',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='会话ID'),
    sa.Column('context_key', sa.String(length=64), nullable=False, comment='上下文键'),
    sa.Column('context_value', sa.Text(), nullable=False, comment='上下文值'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='会话ID'),
    sa.Column('message_type', sa.String(length=10), nullable=False, comment='消息类型（user/ai）'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('message_metadata', sa.JSON(), nullable=True, comment='消息元数据（如推荐结果）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('recommend_type', sa.String(length=10), nullable=False, comment='推荐类型（merchant/attraction）'),
    sa.Column('recommend_id', sa.BigInteger(), nullable=False, comment='推荐对象ID'),
    sa.Column('recommend_reason', sa.String(length=256), nullable=False, comment='推荐理由'),
    sa.Column('weather_info', sa.JSON(), nullable=True, comment='天气信息'),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='推荐分数'),
    sa.Column('is_clicked', sa.Boolean(), nullable=True, comment='是否被点击'),
    sa.Column('feedback', sa.SmallInteger(), nullable=True, comment='用户反馈（1喜欢 0无反馈 -1不喜欢）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intent_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='会话ID'),
    sa.Column('query', sa.Text(), nullable=False, comment='用户查询'),
    sa.Column('intent', sa.String(length=64), nullable=False, comment='识别意图'),
    sa.Column('entities', sa.JSON(), nullable=True, comment='提取实体'),
    sa.Column('confidence', sa.DECIMAL(precision=5, scale=4), nullable=True, comment='置信度'),
    sa.Column('response_time', sa.BigInteger(), nullable=True, comment='响应时间（毫秒）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='经度'),
    sa.Column('accuracy', sa.Float(), nullable=True, comment='定位精度（米）'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='定位来源（browser/ip/manual）'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='用户代理'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_ratings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=False, comment='商家ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=1), nullable=False, comment='评分（0-5）'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评价内容'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('keyword', sa.String(length=128), nullable=False, comment='搜索关键词'),
    sa.Column('search_type', sa.String(length=32), nullable=False, comment='搜索类型（food/attraction）'),
    sa.Column('result_count', sa.Integer(), nullable=True, comment='结果数量'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='分享用户ID'),
    sa.Column('share_type', sa.String(length=10), nullable=False, comment='分享类型（merchant/attraction）'),
    sa.Column('share_id', sa.BigInteger(), nullable=False, comment='分享对象ID'),
    sa.Column('share_channel', sa.String(length=32), nullable=False, comment='分享渠道（wechat/moments/link）'),
    sa.Column('share_url', sa.String(length=512), nullable=False, comment='分享链接'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='访问次数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('merchant_id', sa.BigInteger(), nullable=True, comment='商家ID'),
    sa.Column('attraction_id', sa.BigInteger(), nullable=True, comment='景点ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_locations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='位置名称（家、公司等）'),
    sa.Column('address', sa.String(length=256), nullable=False, comment='详细地址'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False, comment='经度'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='城市'),
    sa.Column('district', sa.String(length=64), nullable=True, comment='区县'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认位置'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xiaohongshu_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=True, comment='关联商家ID'),
    sa.Column('attraction_id', sa.BigInteger(), nullable=True, comment='关联景点ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='笔记标题'),
    sa.Column('author', sa.String(length=64), nullable=False, comment='作者昵称'),
    sa.Column('author_avatar', sa.String(length=512), nullable=True, comment='作者头像'),
    sa.Column('publish_time', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='评论数'),
    sa.Column('collect_count', sa.Integer(), nullable=True, comment='收藏数'),
    sa.Column('content', sa.Text(), nullable=True, comment='笔记内容'),
    sa.Column('summary', sa.Text(), nullable=True, comment='内容摘要'),
    sa.Column('pros', sa.JSON(), nullable=True, comment='优点列表'),
    sa.Column('cons', sa.JSON(), nullable=True, comment='缺点列表'),
    sa.Column('tips', sa.JSON(), nullable=True, comment='避坑提示'),
    sa.Column('original_url', sa.String(length=512), nullable=False, comment='原文链接'),
    sa.Column('images', sa.JSON(), nullable=True, comment='笔记图片'),
    sa.Column('source', sa.String(length=32), nullable=True, comment='数据来源'),
    sa.Column('source_id', sa.String(length=64), nullable=True, comment='来源ID'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态（0禁用 1正常）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xiaohongshu_notes')
    op.drop_table('user_locations')
    op.drop_table('user_favorites')
    op.drop_table('share_logs')
    op.drop_table('search_history')
    op.drop_table('merchant_ratings')
    op.drop_table('location_logs')
    op.drop_table('intent_logs')
    op.drop_table('daily_recommendations')
    op.drop_table('chat_history')
    op.drop_table('chat_context')
    op.drop_table('attraction_ratings')
    op.drop_table('users')
    op.drop_table('note_cache')
    op.drop_table('merchants')
    op.drop_table('attractions')
    # ### end Alembic commands ###
